### ISSUE TITLE
Invalid argument supplied for foreach() after adding field to entry type

### ISSUE THREAD

**Issue by JayBox325** [davist11/craft-shopify#13]
I have set up the Craft Shopify plugin on a new build.

I have also created a 'Shopify Product' field in the CMS on my entry within my Products channel.

However, whenever I try to view the product in the back end I get this error (see attached).

Thanks,
Jay
![screen shot 2017-03-23 at 08 32 11](https://cloud.githubusercontent.com/assets/13233809/24238911/c52b2efe-0fa3-11e7-84db-5c7ef762f28d.png)
![screen shot 2017-03-23 at 08 31 31](https://cloud.githubusercontent.com/assets/13233809/24238912/c52c640e-0fa3-11e7-8a1e-a55a3118830c.png)

**Comment by JayBox325** [comment]
This error arose from `https://` being in the store URL supplied in the CMS. Possibility to add some documentation for others that may make this mistake?

**Comment by davist11** [comment]
Ah yeah, you don't want to put a full URL in there, only a hostname. That's why the placeholder says `hostname.myshopify.com`
