### ISSUE TITLE
Very slow response times

### ISSUE THREAD

**Issue by katrinkerber** [davist11/craft-shopify#3]
Thank you so much for such a useful plugin. I am in the process of launching a Craft site that is hooked up to Shopify products and it's working really well.

I have discovered though that the API calls to Shopify increase the TTFB considerably. For example, a page with 25 products has **12s TTFB** with the plugin tags that pull in the Shopify variants and without them the page comes down to **1.8s TTFB**, which is a huge difference.

Is there anything I can do to increase the response time?

I don't know much about APIs, so excuse my ignorance.

**Comment by davist11** [comment]
Have you experimented with using the Craft `{% cache %}` tag at all? Also, depending on how you are hitting the API, you may be able to request things in a different way and use twig to limit the requests. Can you post your template code?

**Comment by katrinkerber** [comment]
Thank you Trevor.

This is my code:
```
<span class="listing__item__price" itemprop="price">
  {% set shopifyProductID = entry.shopifyProductUrl|replace('/[^0-9]+/', '') %}
  {% set shopify = craft.shopify.getProductById({ id: shopifyProductID, fields: 'variants' }) %}
  {% if shopify.variants is not null and shopify.variants|length %}
    {% for variant in shopify.variants %}
      {% if loop.first %}
        &pound;{{ variant.price }}
      {% endif %}
    {% endfor %}
  {% endif %}
</span>
```

If I wrap caching tag around that, all the products display the same price.

**Comment by davist11** [comment]
Is this within a for loop where you are looping through `craft.entries` ?

**Comment by katrinkerber** [comment]
Yup :)

It's this:
```
{% set productCategory = block.category.first() %}
{% set entries = craft.entries.section('products').relatedTo(productCategory) %}
{% for entry in entries %}
  [...]
{% endfor %}
```

**Comment by davist11** [comment]
Perfect, that's exactly why <a href="https://github.com/davist11/craft-shopify#craftshopifygetproductsvariants">getProductsVariants</a> exists, to save API calls. I would definitely recommend wrapping the whole thing in a cache tag as well.

**Comment by katrinkerber** [comment]
Aaaahh! Lightbulb moment! 

Should have studied your documentation more thoroughly.

That's perfect and together with the cache tags the TTFB is now down to an amazing average of **~ 260ms** - woop!

As a note: I did have to up the product limit as [explained here](https://github.com/davist11/craft-shopify/issues/2). I guess if the shop ever gets over the 250 limit I'll have to revisit this again, but for now this is brilliant.

Thank you so much for taking the time to help, I really appreciate it :)

**Comment by davist11** [comment]
Sweet, glad it got you what you needed. You can already pass the limit in as an option. See it in <a href="https://github.com/davist11/craft-shopify#craftshopifygetproducts">this example</a>.
